name: deploy

on:
  push:
    branches: [ master, 0.1.x ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: 0.1.x
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: create tar
      run: |
          tar czf $HOME/WenShu-$GITHUB_RUN_NUMBER.tar.gz .
          rm -rf *        
          mv $HOME/WenShu-$GITHUB_RUN_NUMBER.tar.gz .
          ls
          pwd
    - name: Copy file
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.WEB_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.WEB_PASSWORD }}
        source: "."
        target: "~/Project/WenShu"
