name: test_env

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      PROJECT_NAME: wenshu
      BRANCH_NAME: ${GITHUB_REF##*/}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a single command using the runners shell
    - name: print env
      run: |
        echo GITHUB_REF $GITHUB_REF ${GITHUB_REF##*/}
        echo GITHUB_REPOSITORY $GITHUB_REPOSITORY
        echo GITHUB_EVENT_NAME $GITHUB_EVENT_NAME
        echo $PROJECT_NAME
      
    - name: checkout
      with:
        ref: ${BRANCH_NAME}
